"use client";

import { useState } from "react";
import { Card } from "@/components/ui/card";
import { AddButton, EntryCard, Field, TagInput, Textarea } from "@/components/builder/form-controls";
import { OptionalResumeSections } from "@/components/builder/optional-resume-sections";
import { useResumeContext } from "@/context/resume-context";
import type { Education, Experience, PersonalDetails } from "@/types/resume";

const makeId = () => crypto.randomUUID();
const steps = ["Personal Information + Summary", "Work Experience", "Education", "Skills", "Additional Sections"];

function Section({ title, description, children }: { title: string; description?: string; children: React.ReactNode }) {
  return <section><h2 className="text-xl font-semibold tracking-tight text-slate-900 sm:text-2xl">{title}</h2>{description && <p className="mt-2 text-sm leading-6 text-slate-600">{description}</p>}<div className="mt-6">{children}</div></section>;
}

export function ResumeFormContainer() {
  const { state, dispatch } = useResumeContext();
  const { resume } = state;
  const [currentStep, setCurrentStep] = useState(() => { const value = Number(state.activeSection); return value >= 1 && value <= 5 ? value : 1; });
  const [showErrors, setShowErrors] = useState(false);
  const personal = resume.personalDetails;
  const skills = resume.skillGroups.find((group) => group.id === "primary")?.skills ?? [];
  const updatePersonal = (update: Omit<Partial<PersonalDetails>, "contact"> & { contact?: Partial<PersonalDetails["contact"]> }) => {
    dispatch({ type: "UPDATE_PERSONAL_DETAILS", payload: { ...personal, ...update, contact: { ...personal.contact, ...update.contact } } });
  };
  const setExperience = (items: Experience[]) => dispatch({ type: "SET_EXPERIENCES", payload: items });
  const setEducation = (items: Education[]) => dispatch({ type: "SET_EDUCATION", payload: items });
  const hasPersonalErrors = !personal.firstName.trim() || !personal.lastName.trim() || !personal.headline.trim() || !personal.contact.email.trim() || !personal.contact.phone.trim() || !personal.contact.location.trim() || !resume.professionalSummary.trim();
  const hasExperienceErrors = resume.experiences.some((item) => !item.employer.trim() || !item.role.trim() || !item.location.trim() || !item.startDate || (!item.current && !item.endDate) || !item.description.trim());
  const hasEducationErrors = resume.education.length === 0 || resume.education.some((item) => !item.institution.trim() || !item.degree.trim() || (item.educationType === "college" && !item.fieldOfStudy.trim()) || !item.startDate || (!item.current && !item.endDate));
  const hasSkillsErrors = skills.length === 0;
  const invalidStep = () => currentStep === 1 ? hasPersonalErrors : currentStep === 2 ? hasExperienceErrors : currentStep === 3 ? hasEducationErrors : currentStep === 4 ? hasSkillsErrors : false;
  const goTo = (nextStep: number) => { setCurrentStep(nextStep); setShowErrors(false); dispatch({ type: "SET_ACTIVE_SECTION", payload: String(nextStep) }); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const next = () => { if (invalidStep()) { setShowErrors(true); return; } if (currentStep < steps.length) goTo(currentStep + 1); };

  return <Card aria-labelledby="form-title" className="min-w-0">
    <div className="flex flex-col gap-3 border-b border-slate-200/80 pb-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Resume content</p><h1 id="form-title" className="mt-2 text-2xl font-semibold tracking-tight text-slate-950">Build your resume</h1></div><p className="text-sm font-medium text-slate-500">Step {currentStep} of {steps.length}</p></div>
    <nav className="mt-5 overflow-x-auto pb-1" aria-label="Resume form sections"><ol className="flex min-w-max gap-2">{steps.map((step, index) => { const number = index + 1; return <li key={step}><button type="button" onClick={() => number < currentStep && goTo(number)} disabled={number > currentStep} aria-current={number === currentStep ? "step" : undefined} className={`rounded-full px-3 py-2 text-xs font-semibold transition ${number === currentStep ? "bg-blue-600 text-white shadow-sm" : number < currentStep ? "bg-blue-50 text-blue-700 hover:bg-blue-100" : "bg-slate-100 text-slate-400"}`}>{number}. {step}</button></li>; })}</ol></nav>
    <form className="mt-8" onSubmit={(event) => { event.preventDefault(); next(); }} noValidate>
      {currentStep === 1 && <Section title="Personal information" description="Start with the details recruiters use to contact you."><div className="grid gap-4 sm:grid-cols-2">
        <Field label="First name" required value={personal.firstName} onChange={(event) => updatePersonal({ firstName: event.target.value })} error={showErrors && !personal.firstName.trim() ? "First name is required." : undefined} placeholder="John" />
        <Field label="Last name" required value={personal.lastName} onChange={(event) => updatePersonal({ lastName: event.target.value })} error={showErrors && !personal.lastName.trim() ? "Last name is required." : undefined} placeholder="Doe" />
        <Field label="Professional title" required value={personal.headline} onChange={(event) => updatePersonal({ headline: event.target.value })} error={showErrors && !personal.headline.trim() ? "Professional title is required." : undefined} placeholder="Software Developer" className="sm:col-span-2" />
        <Field label="Email" required type="email" value={personal.contact.email} onChange={(event) => updatePersonal({ contact: { email: event.target.value } })} error={showErrors && !personal.contact.email.trim() ? "Email is required." : undefined} placeholder="john.doe@email.com" />
        <Field label="Phone number" required type="tel" value={personal.contact.phone} onChange={(event) => updatePersonal({ contact: { phone: event.target.value } })} error={showErrors && !personal.contact.phone.trim() ? "Phone number is required." : undefined} placeholder="0912 345 6789" />
        <Field label="Location" required value={personal.contact.location} onChange={(event) => updatePersonal({ contact: { location: event.target.value } })} error={showErrors && !personal.contact.location.trim() ? "Location is required." : undefined} placeholder="Cebu City, Philippines" />
        <Field label="LinkedIn" type="url" value={personal.contact.linkedin} onChange={(event) => updatePersonal({ contact: { linkedin: event.target.value } })} placeholder="linkedin.com/in/johndoe" />
        <Field label="GitHub" type="url" value={personal.contact.github} onChange={(event) => updatePersonal({ contact: { github: event.target.value } })} placeholder="github.com/johndoe" />
        <Field label="Portfolio" type="url" value={personal.contact.website} onChange={(event) => updatePersonal({ contact: { website: event.target.value } })} placeholder="johndoe.dev" />
      </div><div className="mt-8 border-t border-slate-200/80 pt-7"><h2 className="text-xl font-semibold tracking-tight text-slate-900">Professional summary</h2><p className="mt-2 text-sm text-slate-600">Aim for two to four concise sentences.</p><div className="mt-4"><Textarea label="Summary" value={resume.professionalSummary} onChange={(event) => dispatch({ type: "SET_PROFESSIONAL_SUMMARY", payload: event.target.value })} error={showErrors && !resume.professionalSummary.trim() ? "Summary is required." : undefined} maxLength={600} hint={`${resume.professionalSummary.length}/600 characters`} placeholder="Summarize your expertise, strengths, and the value you bring." /></div></div></Section>}
      {currentStep === 2 && <Section title="Work experience" description="This section is optional. Add roles that best demonstrate your impact."><div className="space-y-3">{resume.experiences.map((item, index) => <ExperienceEditor key={item.id} item={item} index={index} showErrors={showErrors} onChange={(nextItem) => setExperience(resume.experiences.map((entry) => entry.id === nextItem.id ? nextItem : entry))} onRemove={() => setExperience(resume.experiences.filter((entry) => entry.id !== item.id))} />)}</div><AddButton onClick={() => setExperience([...resume.experiences, { id: makeId(), employer: "", role: "", location: "", startDate: "", endDate: "", current: false, description: "", highlights: [] }])}>+ Add experience</AddButton></Section>}
      {currentStep === 3 && <Section title="Education" description="Add at least one college, university, or high school entry."><div className="space-y-3">{resume.education.map((item, index) => <EducationEditor key={item.id} item={item} index={index} showErrors={showErrors} onChange={(nextItem) => setEducation(resume.education.map((entry) => entry.id === nextItem.id ? nextItem : entry))} onRemove={() => setEducation(resume.education.filter((entry) => entry.id !== item.id))} />)}</div>{showErrors && resume.education.length === 0 && <p className="mt-3 text-sm text-red-600">Add at least one education entry to continue.</p>}<div className="mt-4 flex flex-wrap gap-3"><AddButton onClick={() => setEducation([...resume.education, blankEducation("college")])}>+ Add college / university</AddButton><AddButton onClick={() => setEducation([...resume.education, blankEducation("highSchool")])}>+ Add high school</AddButton></div></Section>}
      {currentStep === 4 && <Section title="Skills" description="Add the individual skills most relevant to the role you want."><TagInput label="Skills" values={skills} onChange={(nextItems) => dispatch({ type: "SET_SKILLS", payload: nextItems })} placeholder="Type a skill and press Enter" />{showErrors && hasSkillsErrors && <p className="mt-2 text-sm text-red-600">Add at least one skill to continue.</p>}</Section>}
      {currentStep === 5 && <Section title="Additional sections" description="Choose sections that strengthen your resume. These are optional, so add only what is relevant to you."><OptionalResumeSections /></Section>}
      <div className="mt-9 flex items-center justify-between border-t border-slate-200/80 pt-5"><button type="button" onClick={() => goTo(currentStep - 1)} disabled={currentStep === 1} className="min-h-11 rounded-xl border border-slate-200 bg-white/70 px-4 text-sm font-semibold text-slate-700 transition hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-45">← Previous</button>{currentStep < steps.length ? <button type="submit" className="min-h-11 rounded-xl bg-blue-600 px-5 text-sm font-semibold text-white shadow-sm transition hover:bg-blue-700">Next</button> : <button type="submit" className="min-h-11 rounded-xl bg-blue-600 px-5 text-sm font-semibold text-white shadow-sm transition hover:bg-blue-700">Finish →</button>}</div>
    </form>
  </Card>;
}

function ExperienceEditor({ item, index, showErrors, onChange, onRemove }: { item: Experience; index: number; showErrors: boolean; onChange: (item: Experience) => void; onRemove: () => void }) {
  const update = <K extends keyof Experience>(key: K, value: Experience[K]) => onChange({ ...item, [key]: value });
  return <EntryCard title={item.role || item.employer || `Experience ${index + 1}`} onRemove={onRemove}><div className="grid gap-4 sm:grid-cols-2"><Field label="Company" required value={item.employer} onChange={(event) => update("employer", event.target.value)} error={showErrors && !item.employer.trim() ? "Company is required." : undefined} placeholder="Acme Inc." /><Field label="Job title" required value={item.role} onChange={(event) => update("role", event.target.value)} error={showErrors && !item.role.trim() ? "Job title is required." : undefined} placeholder="Software Developer" /><Field label="Location" required value={item.location} onChange={(event) => update("location", event.target.value)} error={showErrors && !item.location.trim() ? "Location is required." : undefined} placeholder="Cebu City, Philippines" /><div className="flex items-end"><label className="flex min-h-11 items-center gap-2 text-sm font-medium text-slate-700"><input type="checkbox" checked={item.current} onChange={(event) => onChange({ ...item, current: event.target.checked, endDate: event.target.checked ? "" : item.endDate })} />Current job</label></div><Field label="Start date" required type="month" value={item.startDate} onChange={(event) => update("startDate", event.target.value)} error={showErrors && !item.startDate ? "Start date is required." : undefined} /><Field label="End date" required={!item.current} type="month" disabled={item.current} value={item.endDate} onChange={(event) => update("endDate", event.target.value)} error={showErrors && !item.current && !item.endDate ? "End date is required." : undefined} /><Textarea label="Description" className="sm:col-span-2" value={item.description} onChange={(event) => update("description", event.target.value)} error={showErrors && !item.description.trim() ? "Description is required." : undefined} placeholder="Describe your responsibilities and achievements." /></div></EntryCard>;
}

function blankEducation(educationType: Education["educationType"]): Education { return { id: makeId(), educationType, institution: "", degree: "", fieldOfStudy: "", location: "", startDate: "", endDate: "", current: false, description: "" }; }

function EducationEditor({ item, index, showErrors, onChange, onRemove }: { item: Education; index: number; showErrors: boolean; onChange: (item: Education) => void; onRemove: () => void }) {
  const update = <K extends keyof Education>(key: K, value: Education[K]) => onChange({ ...item, [key]: value });
  const isCollege = item.educationType === "college";
  return <EntryCard title={item.institution || `${isCollege ? "College / University" : "High School"} ${index + 1}`} onRemove={onRemove}><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium text-slate-700">Education level<select value={item.educationType} onChange={(event) => onChange({ ...item, educationType: event.target.value as Education["educationType"], fieldOfStudy: event.target.value === "highSchool" ? "" : item.fieldOfStudy })} className="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 bg-white/80 px-3 text-sm text-slate-900 shadow-sm focus:border-blue-500 focus:outline-none"><option value="college">College / University</option><option value="highSchool">High School</option></select></label><Field label="School" required value={item.institution} onChange={(event) => update("institution", event.target.value)} error={showErrors && !item.institution.trim() ? "School is required." : undefined} placeholder={isCollege ? "University of San Carlos" : "Cebu City National Science High School"} /><Field label={isCollege ? "Degree" : "Strand / Program"} required value={item.degree} onChange={(event) => update("degree", event.target.value)} error={showErrors && !item.degree.trim() ? `${isCollege ? "Degree" : "Strand / Program"} is required.` : undefined} placeholder={isCollege ? "Bachelor of Science" : "STEM"} />{isCollege && <Field label="Field of study" required value={item.fieldOfStudy} onChange={(event) => update("fieldOfStudy", event.target.value)} error={showErrors && !item.fieldOfStudy.trim() ? "Field of study is required." : undefined} placeholder="Computer Science" />}<Field label="Start date" required type="month" value={item.startDate} onChange={(event) => update("startDate", event.target.value)} error={showErrors && !item.startDate ? "Start date is required." : undefined} /><div className="flex items-end"><label className="flex min-h-11 items-center gap-2 text-sm font-medium text-slate-700"><input type="checkbox" checked={item.current} onChange={(event) => onChange({ ...item, current: event.target.checked, endDate: event.target.checked ? "" : item.endDate })} />Currently studying</label></div><Field label="End date" required={!item.current} type="month" disabled={item.current} value={item.endDate} onChange={(event) => update("endDate", event.target.value)} error={showErrors && !item.current && !item.endDate ? "End date is required." : undefined} /></div></EntryCard>;
}
